spring.application.name=Resume Analyser
# MongoDB URI with Keep-Alive for LLM processing delays
spring.data.mongodb.uri=${MONGO_ATLAS_STRING}
spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
server.port=8080

spring.ai.retry.max-attempts=1

# File Size Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB